version: '3.7'
services:
  ghostfolio:
    container_name: ghostfolio
    image: ghostfolio:{{VERSION}}
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - redis
    env_file:
      - ../.env
    environment:
      - NODE_ENV=production

  postgres:
    image: postgres:12
    container_name: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    env_file:
      - ../.env
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: 'redis:alpine'
    container_name: redis
    restart: unless-stopped
    ports:
      - 6379:6379

volumes:
  portainer_data:
  postgres:
    name: ghostfolio-db
